apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
